Добавление PetPhoto
AlexEng-r/PetFamily pull request #4
Opened 2024-08-10 17:36 UTC by AlexEng-r

2024-08-10 17:43 UTC, YADARAN1 requested changes

2024-08-10 17:43 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Pets/Pet.cs
> +    public List<PetPhoto> PetPhotos { get; private set; }
Ты по-моему перепутал, у животных не должно быть листа с животными, этот лист должен быть у Волонтёра, перечитай задание по модели волонтёра

2024-08-10 17:43 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/PetPhotos/PetPhoto.cs
> +
Перечитай задание по созданию фотки, должен быть Guid Id

2024-08-10 17:43 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Names/Name.cs
> +    public string Patronymic { get; private set; }
Измени название класса на FullName

2024-08-10 17:48 UTC, AlexEng-r commented on backend/src/PetFamily.Domain/Pets/Pet.cs
> +    public List<PetPhoto> PetPhotos { get; private set; }
не перепутал. Добавить домашнему животному поле со списком фотографий PetPhoto.

2024-08-10 17:50 UTC, AlexEng-r commented on backend/src/PetFamily.Domain/PetPhotos/PetPhoto.cs
> +
отнаследованный гуид не подходит?

2024-08-11 09:25 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/Pets/Pet.cs
> +    public List<PetPhoto> PetPhotos { get; private set; }
Да, извиняюсь, я прочитал не так

2024-08-11 09:26 UTC, YADARAN1 commented on backend/src/PetFamily.Domain/PetPhotos/PetPhoto.cs
> +
Ещё раз приношу извинения, не заметил

2024-08-11 10:00 UTC, YADARAN1 approved these changes

2024-08-12 18:38 UTC, merged