Добавление волонтера
AlexEng-r/PetFamily pull request #8
Opened 2024-08-19 20:14 UTC by AlexEng-r

2024-08-20 06:13 UTC, YaraOduvanchik requested changes

2024-08-20 06:13 UTC, YaraOduvanchik commented on backend/src/PetFamily.API/Controllers/VolunteerController.cs
> +    [HttpPost("create")]
Тут ненужно писать "create", так как метод уже называется Create

2024-08-20 06:13 UTC, YaraOduvanchik commented on backend/src/PetFamily.Infrastructure/Repositories/VolunteersRepository.cs
> +    public Task<bool> AnyByPhone(ContactPhone phone, CancellationToken cancellationToken = default)
Ты забыл написать async

2024-08-20 06:13 UTC, YaraOduvanchik commented on backend/src/PetFamily.Infrastructure/Repositories/VolunteersRepository.cs
> +        => _dbContext.Volunteers.AnyAsync(x => x.Phone == phone, cancellationToken);
А тут await

2024-08-20 13:25 UTC, AlexEng-r commented on backend/src/PetFamily.Infrastructure/Repositories/VolunteersRepository.cs
> +    public Task<bool> AnyByPhone(ContactPhone phone, CancellationToken cancellationToken = default)
Зачем? нам тут эвейтить ничего не надо

2024-08-20 13:26 UTC, AlexEng-r commented on backend/src/PetFamily.Infrastructure/Repositories/VolunteersRepository.cs
> +        => _dbContext.Volunteers.AnyAsync(x => x.Phone == phone, cancellationToken);
аналогично

2024-08-20 13:43 UTC, YaraOduvanchik requested changes

2024-08-20 13:43 UTC, YaraOduvanchik commented on backend/src/PetFamily.Infrastructure/Repositories/VolunteersRepository.cs
> +    public Task<bool> AnyByPhone(ContactPhone phone, CancellationToken cancellationToken = default)
1. У тебя метод возвращает Task, если ты не используешь async, то и Task ненадо
2. У тебя в методе есть метод AnyAsync, так что нуобходимо использовать async

2024-08-20 13:43 UTC, YaraOduvanchik commented on backend/src/PetFamily.Infrastructure/Repositories/VolunteersRepository.cs
> +        => _dbContext.Volunteers.AnyAsync(x => x.Phone == phone, cancellationToken);
Необходимо использовать await перед вызовом асинхронного метода AnyAsync, чтобы он выполнился корректно

2024-08-20 13:44 UTC, AlexEng-r commented on backend/src/PetFamily.Infrastructure/Repositories/VolunteersRepository.cs
> +    public Task<bool> AnyByPhone(ContactPhone phone, CancellationToken cancellationToken = default)
я про то что мы внутри метода ничего не эвейтим, мы просто можем передать таск наружу

2024-09-01 06:02 UTC, YaraOduvanchik approved these changes

2024-09-01 06:09 UTC, merged